{
    'name': 'Barcode WMS',
    'version': '19.0.0.1',
    'license': 'LGPL-3',
    'category': 'Inventory',

    'author': 'Odoo Premium',
    'website': 'https://www.odoopremium.com/app/barcode_wms',

    'depends': ['sale_stock', 'purchase_stock', 'barcodes'],

    'data': [
        'views/barcode_wms.xml',
        'views/stock_picking.xml',
        'views/stock_warehouse.xml',
        'views/res_config_settings.xml',
        'views/ir_actions_client.xml',
        'views/ir_ui_menu.xml',
        'views/barcode_wms_operations.xml',
        'views/stock_picking_barcode.xml',
        'views/stock_move_line_barcode.xml',
        'views/stock_quant_barcode.xml',
        'views/barcode_wms_client_action.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
    ],

    #'post_init_hook': 'post_init_hook',

    'assets': {
        'web.assets_backend': [
            # Xml files
            'barcode_wms/static/src/component/Controllers/inventoryLine.xml',
            'barcode_wms/static/src/component/BarcodeScreen/BarcodeScreen.xml',
            'barcode_wms/static/src/component/BarcodeCamera/BarcodeCamera.xml',
            'barcode_wms/static/src/component/Components/Components.xml',
            'barcode_wms/static/src/component/Components/StockMove.xml',
            'barcode_wms/static/src/component/Components/SearchBar.xml',
            'barcode_wms/static/src/component/Components/EditMove.xml',
            'barcode_wms/static/src/component/Components/EditLine.xml',
            'barcode_wms/static/src/component/Components/AddMove.xml',
            'barcode_wms/static/src/component/Components/Pagination.xml',
            'barcode_wms/static/src/component/Components/CollapsableRow.xml',
            'barcode_wms/static/src/component/Components/ProductDetails.xml',
            'barcode_wms/static/src/component/Components/SelectDropdown.xml',
            'barcode_wms/static/src/component/Components/WarehouseDetails.xml',
            'barcode_wms/static/src/component/Components/NotificationSound.xml',
            'barcode_wms/static/src/component/StockAdjustments/StockAdjustments.xml',
            'barcode_wms/static/src/component/InventoryTransfer/InventoryTransfer.xml',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperation.xml',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperations.xml',
            'barcode_wms/static/src/component/InventoryAdjustments/InventoryAdjustments.xml',

            # Fonts and Scss files
            'barcode_wms/static/fonts/font.css',
            'barcode_wms/static/src/scss/style.scss',
            'barcode_wms/static/src/component/BarcodeScreen/BarcodeScreen.scss',
            'barcode_wms/static/src/component/Components/Components.scss',
            'barcode_wms/static/src/component/Components/SearchBar.scss',
            'barcode_wms/static/src/component/Components/SelectDropdown.scss',
            'barcode_wms/static/src/component/Components/ProductDetails.scss',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperation.scss',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperations.scss',

            #Js files
            # 'barcode_wms/static/src/component/Controllers/inventoryLine.js',  # TODO: Rewrite for Odoo 19 - uses deprecated ListController
            'barcode_wms/static/src/component/BarcodeScreen/BarcodeScreen.js',
            'barcode_wms/static/src/component/BarcodeCamera/BarcodeCamera.js',
            'barcode_wms/static/src/component/Components/Components.js',
            'barcode_wms/static/src/component/Components/StockMove.js',
            'barcode_wms/static/src/component/Components/EditMove.js',
            'barcode_wms/static/src/component/Components/EditLine.js',
            'barcode_wms/static/src/component/Components/SearchBar.js',
            'barcode_wms/static/src/component/Components/AddMove.js',
            'barcode_wms/static/src/component/Components/Pagination.js',
            'barcode_wms/static/src/component/Components/CollapsableRow.js',
            'barcode_wms/static/src/component/Components/ProductDetails.js',
            'barcode_wms/static/src/component/Components/SelectDropdown.js',
            'barcode_wms/static/src/component/Components/WarehouseDetails.js',
            'barcode_wms/static/src/component/Components/NotificationSound.js',
            'barcode_wms/static/src/component/StockAdjustments/StockAdjustments.js',
            'barcode_wms/static/src/component/InventoryTransfer/InventoryTransfer.js',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperation.js',
            'barcode_wms/static/src/component/WarehouseOperations/WarehouseOperations.js',
            'barcode_wms/static/src/component/InventoryAdjustments/InventoryAdjustments.js',
            'barcode_wms/static/src/main_menu/main_menu.js',
            'barcode_wms/static/src/main_menu/main_menu.xml',
            'barcode_wms/static/src/kanban/barcode_wms_kanban_controller.js',
            'barcode_wms/static/src/kanban/barcode_wms_kanban_renderer.js',
            'barcode_wms/static/src/kanban/barcode_wms_kanban_view.js',
            'barcode_wms/static/src/kanban/barcode_wms_kanban_renderer.xml',
            'barcode_wms/static/src/main_component/main_component.js',
            'barcode_wms/static/src/main_component/main_component.xml',
            'barcode_wms/static/src/models/lazy_barcode_cache.js',
            'barcode_wms/static/src/models/barcode_model.js',
            'barcode_wms/static/src/models/barcode_quant_model.js',
            'barcode_wms/static/src/models/barcode_picking_model.js',
            'barcode_wms/static/src/models/barcode_object.js',
            'barcode_wms/static/src/components/backorder_dialog.js',
            'barcode_wms/static/src/components/backorder_dialog.xml',
            'barcode_wms/static/src/components/line_component.js',
            'barcode_wms/static/src/components/line_component.xml',
            'barcode_wms/static/src/components/grouped_line.js',
            'barcode_wms/static/src/components/grouped_line.xml',
            'barcode_wms/static/src/components/product_image_dialog.js',
            'barcode_wms/static/src/components/product_image_dialog.xml',
            'barcode_wms/static/src/js/barcode_wms_sml_form.js',
            #'barcode_wms/static/src/widgets/digipad.js',
            #'barcode_wms/static/src/widgets/digipad.xml',
            #'barcode_wms/static/src/widgets/unlink_button.js',
            #'barcode_wms/static/src/widgets/unlink_button.xml',
            #'barcode_wms/static/src/widgets/set_quant_stock_move_line.js',
            #'barcode_wms/static/src/widgets/image_preview.js',
            #'barcode_wms/static/src/widgets/image_preview.xml',
            'barcode_wms/static/src/scss/barcode_wms.scss',
        ],
    },

    'demo': [],

    'tests': [],

    'maintainer': 'Odoo Premium',
    'url': 'https://github.com/odoopremium/stock/tree/16.0',
    'live_test_url': 'https://runbot16.odoopremium.com',

    'sequence': 1,
    'installable': True,
    'application': True,
    'auto_install': False,

    #'external_dependencies': {'python': []}
}
