# -*- coding: utf-8 -*-
# Copyright © 2023 Projet (https://bulutkobi.io)
# Part of Projet License. See LICENSE file for full copyright and licensing details.
{
    'name': 'Field Service',
    'version': '19.0.1.0',
    'author': 'Projet',
    'website': 'https://bulutkobi.io',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'stock',
        'mail',
        'sms',
        'sale',
        'purchase',
        'crm',
        'sla',
        'l10n_tr_address',
        'delivery',
        'stock_barcode',
        'hr_timesheet',
        'stock_picking_batch',
        'stock_delivery',
    ],
    'data': [
        'data/data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'reports/fsm_task.xml',
        'views/fsm_project.xml',
        'views/fsm_task.xml',
        'views/fsm_type.xml',
        'views/fsm_stage.xml',
        'views/fsm_button.xml',
        'views/fsm_package.xml',
        'views/fsm_reason.xml',
        'views/fsm_todo.xml',
        'views/fsm_flow.xml',
        'views/fsm_form.xml',
        'views/fsm_auto.xml',
        'views/fsm_service.xml',
        'views/fsm_timesheet.xml',
        'views/fsm_appointment.xml',
        'views/sla_ticket.xml',
        'views/product_template.xml',
        'views/stock_location.xml',
        'views/stock_warehouse.xml',
        'views/stock_picking.xml',
        'views/stock_quant.xml',
        'views/stock_lot.xml',
        'views/sale_order.xml',
        'views/res_partner.xml',
        'views/res_users.xml',
        'views/crm_team.xml',
        'wizards/fsm_project_confirm.xml',
        'wizards/fsm_stage_reason.xml',
        'wizards/fsm_stage_change.xml',
        'wizards/fsm_reason_change.xml',
        'wizards/fsm_task_create.xml',
        'wizards/fsm_task_import.xml',
        'wizards/fsm_task_user_assign.xml',
        'wizards/fsm_task_service_change.xml',
        'wizards/fsm_task_delivery_select.xml',
        'wizards/fsm_appointment_date_change.xml',
        'wizards/stock_location_user_assign.xml',
        'views/ir_ui_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'fsm/static/src/lib/filepond/filepond.css',
            'fsm/static/src/lib/filepond/filepond.js',
            'fsm/static/src/lib/filepond/filepond_image_preview.css',
            'fsm/static/src/lib/filepond/filepond_image_preview.js',
            'fsm/static/src/lib/filepond/filepond_validate_type.js',
            'fsm/static/src/lib/filepond/filepond_validate_size.js',
            'fsm/static/src/scss/backend.scss',
            'fsm/static/src/xml/backend.xml',
            'fsm/static/src/js/backend.js',
            #'fsm/static/src/js/wms.js',
        ],
    },
    'installable': True,
    'application': True,
}
