# -*- coding: utf-8 -*-
from odoo import models, fields


class FsmApiLogWorldline(models.Model):
    _name = 'fsm.api.log.worldline'
    _description = 'Field Service: Worldline API Logs'
    _sequence = 'id desc'

    name = fields.Char()
    code = fields.Char()

    username = fields.Char() # username # Username
    password = fields.Char() # password # Password
    talepNo = fields.Char() # customerOrderId # customerOrderId
    bildirenBankaKodu = fields.Char() # reportingBankCode # ---
    bankaTalepNo = fields.Char() # bankRequestNumber # ---
    talepTipi = fields.Char() # orderType # orderType
    cagriArizaSebebi = fields.Char() # faultReason # ---
    musteriUiyNo = fields.Char() # customerMerchantId # ---
    musteriUiyTerminalNo = fields.Char() # customerMerchantTerminalId # ---
    uiyNo = fields.Char() # merchantId # setup.merchantId
    uiyTerminalNo = fields.Char() # setupKey # setup.setupKey
    mukellefUiyUnvaniAdi = fields.Char() # merchantName # merchant.name
    mukellefUiyAdresi = fields.Char() # merchantPrimaryAddress # merchant.primaryAddress.address
    mukellefUiyIlcesi = fields.Char() # merchantPrimaryAddressTownName # merchant.primaryAddress.town.name
    mukellefUiyIli = fields.Char() # merchantPrimaryAddressCityName # merchant.primaryAddress.city.name
    mukellefUiyYetkiliAd = fields.Char() # merchantPrimaryAddressContactName # merchant.primaryAddress.contactName
    mukellefUiyYetkiliSoyad = fields.Char() # merchantPrimaryAddressContactName # merchant.primaryAddress.contactName
    mukellefUiyYetkiliUnvani = fields.Char() # merchantAuthorizedTitle # ---
    mukellefUiyVergiDairesi = fields.Char() # merchantTaxOffice # merchant.taxOffice
    mukellefUiyVergiNo = fields.Char() # merchantTaxNumber # merchant.taxNumber
    mukellefUiyTel1 = fields.Char() # merchantPrimaryAddressPhoneNumber1 # merchant.primaryAddress.phoneNumber1
    mukellefUiyTel2 = fields.Char() # merchantPrimaryAddressPhoneNumber2 # merchant.primaryAddress.phoneNumber2
    mukellefUiyGsmTel = fields.Char() # merchantPrimaryAddressMobile # merchant.primaryAddress.mobile
    mukellefUiyEmail = fields.Char() # merchantPrimaryAddressEmail # merchant.primaryAddress.email
    mukellefUiyMersisNo = fields.Char() # merchantPrimaryAddressMersisNumber # merchant.primaryAddress.mersisNumber
    mukellefUiyTicaretSicilNo = fields.Char() # merchantPrimaryAddressTradeRegistrationNumber # merchant.primaryAddress.tradeRegistrationNumber
    mukellefUiyEsnafSicilNo = fields.Char() # merchantTradeRecordNumber # ---
    altMusteriYeriFarkli = fields.Char() # isSubMerchantAddress # ---
    altMusteriUiyUnvaniAdi = fields.Char() # subMerchantName # ---
    altMusteriUiyAdresi = fields.Char() # subMerchantAddress # ---
    altMusteriUiyIlcesi = fields.Char() # subMerchantTown # ---
    altMusteriUiyIli = fields.Char() # subMerchantCity # ---
    altMusteriUiyYetkiliAd = fields.Char() # subMerchantAuthorizedFirstName # ---
    altMusteriUiyYetkiliSoyad = fields.Char() # subMerchantAuthorizedLastName # ---
    altMusteriUiyYetkiliUnvani = fields.Char() # subMerchantAuthorizedTitle # ---
    altMusteriUiyVergiDairesi = fields.Char() # subMerchantTaxOffice # ---
    altMusteriUiyVergiNo = fields.Char() # subMerchantTaxNumber # ---
    altMusteriUiyTel1 = fields.Char() # subMerchantPhone1 # ---
    altMusteriUiyTel2 = fields.Char() # subMerchantPhone2 # ---
    altMusteriUiyGsmTel = fields.Char() # subMerchantMobilePhone # ---
    altMusteriUiyEmail = fields.Char() # subMerchantEmail # ---
    altMusteriUiyMersisNo = fields.Char() # subMerchantMersisNumber # ---
    altMusteriUiyTicaretSicilNo = fields.Char() # subMerchantTradeRegistrationNumber # ---
    altMusteriUiyEsnafSicilNo = fields.Char() # subMerchantTradeRecordNumber # ---
    hizmetYeriFarkli = fields.Char() # isServiceAddress # ---
    hizmetYeriUiyUnvaniAdi = fields.Char() # serviceAddressName # merchant.serviceAddress.name
    hizmetYeriUiyAdresi = fields.Char() # serviceAddressAddress # merchant.serviceAddress.address
    hizmetYeriUiyIlcesi = fields.Char() # serviceAddressTown # merchant.serviceAddress.town
    hizmetYeriUiyIli = fields.Char() # serviceAddressCity # merchant.serviceAddress.city
    hizmetYeriUiyYetkiliAd = fields.Char() # serviceAddressContactName # merchant.serviceAddress.contactName
    hizmetYeriUiyYetkiliSoyad = fields.Char() # serviceAddressContactName # merchant.serviceAddress.contactName
    hizmetYeriUiyYetkiliUnvani = fields.Char() # serviceAddressAuthorizedTitle # ---
    hizmetYeriUiyVergiDairesi = fields.Char() # merchantTaxOffice # merchant.taxOffice
    hizmetYeriUiyVergiNo = fields.Char() # merchantTaxNumber # merchant.taxNumber
    hizmetYeriUiyTel1 = fields.Char() # serviceAddressPhoneNumber1 # merchant.serviceAddress.phoneNumber1
    hizmetYeriUiyTel2 = fields.Char() # serviceAddressPhoneNumber2 # merchant.serviceAddress.phoneNumber2
    hizmetYeriUiyGsmTel = fields.Char() # serviceAddressMobile # merchant.serviceAddress.mobile
    hizmetYeriUiyEmail = fields.Char() # serviceAddressEmail # merchant.serviceAddress.email
    hizmetYeriUiyMersisNo = fields.Char() # serviceAddressMersisNumber # merchant.serviceAddress.mersisNumber
    hizmetYeriUiyTicaretSicilNo = fields.Char() # serviceAddressTradeRegistrationNumber # ---
    hizmetYeriUiyEsnafSicilNo = fields.Char() # serviceAddressMerchantTradeRecordNumber # ---
    cagriAciklama = fields.Char() # orderDescription # orderDescription
    musteriOnceligi = fields.Char() # customerPriority # ---
    bankaSubeKodu = fields.Char() # bankBranchCode # ---
    sektor = fields.Char() # sector # ---
    cihazModel = fields.Char() # productModel # products.model
    cihazSeriNo = fields.Char() # productSerialReference # product.Serial.Reference
    uygulamaVersiyonNo = fields.Char() # applicationVersion # setup.applications.version
    talebiIletenKullanici = fields.Char() # requestInitiatorUser # ---
    projeAdi = fields.Char() # projectId # project.id
    garantiKapsaminda = fields.Char() # underWarranty # ---
    yeniUyeNo = fields.Char() # newMemberNumber # ---
    yeniTermNo = fields.Char() # newTerminalNumber # ---
    yeniFirmaAdi = fields.Char() # newCompanyName # ---
    channelinfo = fields.Char() # channelInfo # ---
    stockstate = fields.Char() # stockState # ---
    billingstate = fields.Char() # billingState # ---
    cargodate = fields.Char() # cargoDate # ---
    sicilno = fields.Char() # productSerialNumber # products.serialNumber
    izinYazisiTarihi = fields.Char() # permissionLetterDate # ---
    bankaSiparisNo = fields.Char() # bankOrderNumber # ---
    RFU1 = fields.Char() # rfu1 # ---
    RFU2 = fields.Char() # rfu2 # ---
    RFU3 = fields.Char() # rfu3 # ---
    RFU4 = fields.Char() # rfu4 # ---
    RFU5 = fields.Char() # rfu5 # ---
    projeBaslangicTarihi = fields.Char() # projectStartDate # ---
    projeGunSayisi = fields.Char() # projectDurationDays # ---
    aksesuar = fields.Char() # accessories # ---
